# Permalinks
#
permalink:           pretty

# Setup
title:               Konstantin Reido
tagline:             'personal blog'
description:         ''
# baseurl:             ''
# url:                 ''
paginate:            5

disqus_shortname: konstantinreido
# google_analytics:

# About/contact
author:
  name:              Konstantin Reido
  url:               https://twitter.com/KonstantinReido
  email:             konstantin.reido@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
  - jekyll-gist
